### PR TITLE
Temporary fix for String, Int32 and Bool on the Hololens2 

### PR DESCRIPTION
**Pull request by narious**
The issue was on Unity Editor, String, Int32 and Bool were being properly subscribed to on RosBridge however, after deploying onto the Hololens2 (through appx package on the web server) the Unity Application on the Hololene2 would no longer subscribe to those topics i.e. not appearing on RosBrdige. Redefining the types String, Int32 and Bool in RosSharpMessages appears tohave fixed this. However, it doesn't fix the problem completly (thus temporary fix); but its working. It maybe a problem with importing on the Hololens2

Also wrote some example subscribers for these messages in scripts.

Also a small fix for differentiating colors in spherelist and cubelist

### CODE REVIEW

**Review by steven-lay — COMMENTED** [review]
There are some modifications that shouldn't be together in https://github.com/hri-group/arviz/pull/2/commits/048deb109970b7aa5efe8c696ef4f07589302bdd - namely the changes to WSATestCertificate.pfx (and WSATestCertificate.pfx.meta) as well as ProjectSettings.asset.

I'm guilty of doing it as well.

Also @owanachanaki

**Comment by owanachanaki** [comment]
Hi, 
Have you tried to be explicit in declaring parameter type when using Bool (MessageTypes.Std.Bool instead of just Bool)?

**Comment by narious** [comment]
Yeah, but still had the issue though

**Comment by steven-lay** [comment]
Instead of undoing your additions
with extra commits, it'll be better to just force push changes to the original commits with the corrections

**Pull request closed without merging**
